apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy-cpu
spec:
  replicas: 20
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 200Mi