apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
  - name: my-nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
      
# kubectl create –f nginx.pod.yml --save-config
# kubectl describe pod [pod-name]
# kubectl apply –f nginx.pod.yml
# kubectl exec [pod-name] -it sh
# kubectl edit -f nginx.pod.yml
# Kubectl delete –f nginx.pod.yml

# To exec into container use:
# kubectl exec pod-name -it sh