apiVersion: v1
kind: Pod
metadata:
  name: nodeapp1-pod
  labels:
    app: nodeapp1
    rel: latest
spec:
  containers:
  - name: nodeapp1
    image: pietronromano/nodeapp1:latest
    ports: # Note, "port" isn't valid here, only the internally used containerport
    - containerPort: 8080
    resources: {}
      
# kubectl create –f nodeapp1.pod.yml --save-config
# kubectl describe pod [pod-name]
# kubectl apply –f nodeapp1.pod.yml
# kubectl exec [pod-name] -it sh
# kubectl edit -f nodeapp1.pod.yml
# Kubectl delete –f nodeapp1.pod.yml

# To exec into container use:
# kubectl exec pod-name -it sh