apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp2-dep
  labels:
    app: nodeapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp2
  template:
    metadata:
      labels:
        app: nodeapp2
    spec:
      containers:
      - name: nodeapp2
        image: pietronromano/nodeapp2:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)

---
apiVersion: v1
kind: Service
metadata:
 name: nodeapp2-lb
spec:
 type: LoadBalancer
 selector:
    app: nodeapp2
 ports:
 - port: 82
   targetPort: 8080