# src: https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: deploy-nginx
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: two-containers
#   template:
#     metadata:
#       labels:
#         app: two-containers
#     spec:
#       nodeSelector:
#         "kubernetes.io/os": linux
#       containers:
#       - name: nginx-container
#         image: nginx
#         ports:
#         - containerPort: 80
#         volumeMounts:
#         - name: shared-data
#           mountPath: /usr/share/nginx/html
#       - name: debian-container
#         image: debian
#         command: ["/bin/sh"]
#         args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]
#         volumeMounts:
#         - name: shared-data
#           mountPath: /pod-data
#       # restartPolicy: Never
#       volumes:
#       - name: shared-data
#         emptyDir: {}
# ---
apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels:
    app: two-containers
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: debian-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
