version: "3.8"
services:
  web:
    container_name: webapp
    build: 
      dockerfile: Dockerfile
      context: .
      # context: app-dotnet
    ports:
    - "8008:80"
    environment:
      ConnectionStrings__WebAppContext: "Server=db;Database=ProductsDB;User=sa;Password=@Aa123456789;Encrypt=False"
    depends_on:
    - db

  db:
    container_name: mssql-db
    image: "mcr.microsoft.com/mssql/server:2022-RTM-ubuntu-20.04"
    # image: "mcr.microsoft.com/mssql/server:2022-latest"
    expose:
    - "1433"
    environment:
      SA_PASSWORD: "@Aa123456789"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"