# nodeapp2 version

FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production 
COPY . .
EXPOSE 8080

# For Alpine, use apk to add curl if we want to use that for debugging
RUN apk add curl

RUN chown -R node /usr/src/app
USER node
CMD ["node", "app.js", "nodeapp2"]